=head1 PerlX::QuoteOperator

Create new quote-like operators in Perl


=head2 VERSION

    PerlX::QuoteOperator        0.05
    PerlX::QuoteOperator::URL   0.05


=head2 SYNOPSIS

    use PerlX::QuoteOperator quc => {
        -emulate => 'q', 
        -with    => sub ($) { uc $_[0] }, 
    };
    
    say quc/do i have to $hout/;
    
    # => DO I HAVE TO $HOUT


=head2 DEPENDENCIES

    Devel::Declare
    Text::Balanced      (for alternative parser)
    

=head2 SUPPORT AND DOCUMENTATION

After installing, you can find documentation for this module with the
perldoc command.

    perldoc PerlX::QuoteOperator


=head2 COPYRIGHT AND LICENCE

Copyright (C) 2009-2015 Barry Walsh (Draegtun Systems Ltd | L<http://www.draegtun.com>)

This program is free software; you can redistribute it and/or modify it
under the terms of either: the GNU General Public License as published
by the Free Software Foundation; or the Artistic License.

See http://dev.perl.org/licenses/ for more information.

