=head1 PerlX::QuoteOperator

Create new quote-like operators in Perl


=head2 VERSION

    PerlX::QuoteOperator        0.01
    PerlX::QuoteOperator::URL   0.01


=head2 SYNOPSIS

    use PerlX::QuoteOperator quc => {
        -emulate => 'q', 
        -with    => sub ($) { uc $_[0] }, 
    };
    
    say quc/do i have to $hout/;
    
    # => DO I HAVE TO $HOUT


=head2 INSTALLATION

To install this module, run the following commands:

	perl Build.PL
	./Build
	./Build test
	./Build install


=head2 DEPENDENCIES

    Devel::Declare
    LWP::Simple         (for PerlX::QuoteOperator::URL)
    

=head2 SUPPORT AND DOCUMENTATION

After installing, you can find documentation for this module with the
perldoc command.

    perldoc PerlX::QuoteOperator


=head2 COPYRIGHT AND LICENCE

Copyright (C) 2009 Barry Walsh (Draegtun Systems Ltd)

This program is free software; you can redistribute it and/or modify it
under the terms of either: the GNU General Public License as published
by the Free Software Foundation; or the Artistic License.

See http://dev.perl.org/licenses/ for more information.

